import React from 'react';
import type { Metadata } from 'next';
import { FileText, ShieldAlert } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Terms of Service & Disclaimer - NicheCalc Pro',
  description: 'Read the Terms of Service and Financial Disclaimer for NicheCalc Pro. All tools are mathematical estimates and not legal or tax advice.',
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-4xl px-4 py-12 sm:px-6 lg:px-8 text-slate-300">
      {/* Title */}
      <div className="text-center mb-10">
        <div className="inline-flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-500/10 text-blue-400 mb-4">
          <FileText className="h-6 w-6" />
        </div>
        <h1 id="terms-heading" className="text-3xl font-black tracking-tight text-white sm:text-4xl">
          Terms of Service &amp; Disclaimers
        </h1>
        <p className="mt-2 text-sm text-slate-500">
          Last Updated: June 16, 2026
        </p>
      </div>

      <div className="space-y-8 text-sm leading-relaxed">
        {/* Core Disclaimer Callout */}
        <section className="bg-amber-500/10 p-6 rounded-2xl border border-amber-500/25">
          <div className="flex items-start gap-3">
            <ShieldAlert className="h-6 w-6 text-amber-400 flex-shrink-0 mt-0.5" />
            <div>
              <h2 className="text-base font-bold text-amber-400 mb-2">CRITICAL DISCLAIMER: Estimates Only</h2>
              <p className="text-xs text-amber-300/90 leading-relaxed">
                All calculations, projections, and reports generated by the tools on NicheCalc Pro (including the Gig-Tax Engine, Target Final Grade Estimator, and Rent-to-Own Equity Tracker) are mathematical estimates for educational and research purposes only. They do not constitute formal tax, legal, financial, or academic advice. Never file taxes, sign contracts, or make major financial commitments based solely on these calculators. Consult qualified CPAs, financial advisors, or academic counselors.
              </p>
            </div>
          </div>
        </section>

        {/* Agreement to terms */}
        <section className="bg-slate-900/40 p-6 rounded-2xl border border-slate-800">
          <h2 className="text-base font-bold text-white mb-2">1. Agreement to Terms</h2>
          <p>
            By accessing or using NicheCalc Pro, you agree to be bound by these Terms of Service. If you do not agree to all of the terms and conditions, you are prohibited from using this site and must cease operations immediately.
          </p>
        </section>

        {/* Use License */}
        <section className="bg-slate-900/40 p-6 rounded-2xl border border-slate-800">
          <h2 className="text-base font-bold text-white mb-2">2. Use License</h2>
          <p className="mb-2">
            Permission is granted to temporarily utilize the online calculators for personal, non-commercial transitory usage only. Under this license, you may not:
          </p>
          <ul className="list-disc pl-5 space-y-1 text-slate-400 text-xs">
            <li>Modify or copy the source code of the calculators.</li>
            <li>Use the calculators for commercial commercial advice without independent audits.</li>
            <li>Attempt to reverse engineer or decompile any script on NicheCalc Pro.</li>
            <li>Remove any copyright or proprietary notations from the results.</li>
          </ul>
        </section>

        {/* Limitations */}
        <section className="bg-slate-900/40 p-6 rounded-2xl border border-slate-800">
          <h2 className="text-base font-bold text-white mb-2">3. Limitations of Liability</h2>
          <p>
            In no event shall NicheCalc Pro or its mathematical developers be held liable for any damages (including, without limitation, damages for loss of profits, tax penalties, academic failure, or real estate option forfeitures) arising out of the use or inability to use the calculators, even if NicheCalc Pro has been notified of the possibility of such damage.
          </p>
        </section>

        {/* Accuracy of materials */}
        <section className="bg-slate-900/40 p-6 rounded-2xl border border-slate-800">
          <h2 className="text-base font-bold text-white mb-2">4. Accuracy of Materials & Formulas</h2>
          <p>
            The formulas and calculations displayed on NicheCalc Pro could include technical, typographical, or mathematical errors. NicheCalc Pro does not warrant that any of the materials on its website are accurate, complete, or current. We may make changes to the formulas and calculators contained on our website at any time without notice, but we do not make any commitment to update the materials.
          </p>
        </section>
      </div>
    </div>
  );
}
